import type { ExtendedBooking } from '@/types/hotel/booking/booking';

export const mockBookings: ExtendedBooking[] = [
  {
    id: 'BK001',
    confirmationNumber: 'CNF-2024-001',
    hotelId: 'hotel-1',
    roomId: 'room-301',
    guestId: 'guest-1',
    checkIn: '2024-01-20',
    checkOut: '2024-01-23',
    nights: 3,
    guests: { adults: 2, children: 0 },
    roomRate: 485,
    totalAmount: 1580.25,
    taxes: 125.25,
    fees: [],
    status: 'confirmed',
    paymentStatus: 'paid',
    source: 'direct',
    specialRequests: ['Late check-in', 'Ocean view preferred'],
    assignedRooms: ['301'],
    createdAt: '2024-01-15T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
    guestName: 'Sarah Johnson',
    roomNumber: 'Room 301',
    roomType: 'Ocean Suite',
    paymentMethod: 'Credit Card',
    channelCommission: 0,
    netRevenue: 1580.25
  },
  {
    id: 'BK002',
    confirmationNumber: 'CNF-2024-002',
    hotelId: 'hotel-1',
    roomId: 'room-412',
    guestId: 'guest-2',
    checkIn: '2024-01-18',
    checkOut: '2024-01-21',
    nights: 3,
    guests: { adults: 1, children: 0 },
    roomRate: 325,
    totalAmount: 1058.75,
    taxes: 83.75,
    fees: [],
    status: 'checked-in',
    paymentStatus: 'paid',
    source: 'booking.com',
    specialRequests: ['Early check-in'],
    assignedRooms: ['412'],
    checkinDetails: {
      checkedInAt: '2024-01-18T14:30:00Z',
      checkedInBy: 'John Doe',
      actualRoom: '412',
      keyCardsIssued: 2,
      depositAmount: 100,
      notes: 'Guest arrived early, room was ready'
    },
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-01-18T14:30:00Z',
    guestName: 'Michael Chen',
    roomNumber: 'Room 412',
    roomType: 'Executive Room',
    paymentMethod: 'Credit Card',
    channelCommission: 158.81,
    netRevenue: 899.94
  },
  {
    id: 'BK003',
    confirmationNumber: 'CNF-2024-003',
    hotelId: 'hotel-1',
    roomId: 'room-205',
    guestId: 'guest-3',
    checkIn: '2024-01-25',
    checkOut: '2024-01-28',
    nights: 3,
    guests: { adults: 2, children: 1 },
    roomRate: 185,
    totalAmount: 621.75,
    taxes: 66.75,
    fees: [],
    status: 'pending',
    paymentStatus: 'pending',
    source: 'expedia',
    specialRequests: ['Extra bed for child', 'High floor'],
    assignedRooms: [],
    createdAt: '2024-01-20T16:45:00Z',
    updatedAt: '2024-01-20T16:45:00Z',
    guestName: 'Emma Wilson',
    roomNumber: 'Room 205',
    roomType: 'Standard Room',
    paymentMethod: 'Credit Card',
    channelCommission: 93.26,
    netRevenue: 528.49
  },
  {
    id: 'BK004',
    confirmationNumber: 'CNF-2024-004',
    hotelId: 'hotel-1',
    roomId: 'room-501',
    guestId: 'guest-4',
    checkIn: '2024-01-15',
    checkOut: '2024-01-18',
    nights: 3,
    guests: { adults: 2, children: 0 },
    roomRate: 750,
    totalAmount: 2430.00,
    taxes: 180.00,
    fees: [],
    status: 'checked-out',
    paymentStatus: 'paid',
    source: 'direct',
    specialRequests: ['Presidential suite', 'Airport transfer', 'Champagne service'],
    assignedRooms: ['501'],
    checkoutDetails: {
      checkedOutAt: '2024-01-18T11:00:00Z',
      checkedOutBy: 'Sarah Manager',
      finalAmount: 2430.00,
      refundAmount: 0,
      incidentals: [],
      feedback: 'Excellent service and facilities',
      rating: 5
    },
    createdAt: '2024-01-10T09:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
    guestName: 'Robert Smith',
    roomNumber: 'Room 501',
    roomType: 'Presidential Suite',
    paymentMethod: 'Credit Card',
    channelCommission: 0,
    netRevenue: 2430.00
  },
  {
    id: 'BK005',
    confirmationNumber: 'CNF-2024-005',
    hotelId: 'hotel-1',
    roomId: 'room-302',
    guestId: 'guest-5',
    checkIn: '2024-01-22',
    checkOut: '2024-01-24',
    nights: 2,
    guests: { adults: 1, children: 0 },
    roomRate: 285,
    totalAmount: 616.20,
    taxes: 46.20,
    fees: [],
    status: 'cancelled',
    paymentStatus: 'refunded',
    source: 'airbnb',
    specialRequests: [],
    assignedRooms: [],
    cancellation: {
      cancelledAt: '2024-01-20T10:00:00Z',
      reason: 'Guest request - change of plans',
      refundAmount: 616.20,
      penalty: 0
    },
    createdAt: '2024-01-18T14:20:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
    guestName: 'James Wilson',
    roomNumber: 'Room 302',
    roomType: 'Deluxe Room',
    paymentMethod: 'Credit Card',
    channelCommission: 61.62,
    netRevenue: 0
  }
];

export const statusOptions = [
  { value: 'all', label: 'All Status' },
  { value: 'pending', label: 'Pending' },
  { value: 'confirmed', label: 'Confirmed' },
  { value: 'checked-in', label: 'Checked In' },
  { value: 'checked-out', label: 'Checked Out' },
  { value: 'cancelled', label: 'Cancelled' },
  { value: 'no-show', label: 'No Show' }
];

export const paymentOptions = [
  { value: 'all', label: 'All Payments' },
  { value: 'paid', label: 'Paid' },
  { value: 'pending', label: 'Pending' },
  { value: 'partial', label: 'Partial' },
  { value: 'failed', label: 'Failed' },
  { value: 'refunded', label: 'Refunded' }
];

export const sourceOptions = [
  { value: 'all', label: 'All Sources' },
  { value: 'direct', label: 'Direct' },
  { value: 'booking.com', label: 'Booking.com' },
  { value: 'expedia', label: 'Expedia' },
  { value: 'airbnb', label: 'Airbnb' },
  { value: 'phone', label: 'Phone' },
  { value: 'walk-in', label: 'Walk-in' }
];

export const dateOptions = [
  { value: 'all', label: 'All Dates' },
  { value: 'today', label: 'Today' },
  { value: 'tomorrow', label: 'Tomorrow' },
  { value: 'this-week', label: 'This Week' },
  { value: 'next-week', label: 'Next Week' },
  { value: 'this-month', label: 'This Month' }
];