// Pages barrel export
export { DashboardPage } from './Dashboard'
export { PropertiesPage } from './Properties'
export { PropertyDetailsPage } from './Properties/PropertyDetails'
export { BookingsPage } from './Bookings'
export { BookingDetailsPage } from './Bookings/BookingDetails'
export { RoomsPage } from './Rooms'
export { GuestsPage } from './Guests'
export { GuestDetailsPage } from './Guests/GuestDetails'
export { RevenuePage } from './Revenue'
export { StaffPage } from './Staff'
export { ReportsPage } from './Reports'
export { SettingsPage } from './Settings'
export { LoginPage } from './Auth/Login'
export { NotFoundPage } from './NotFound'