import type { ExtendedGuest } from '@/types/hotel/guest/guest';

export const mockGuests: ExtendedGuest[] = [
  {
    id: 'guest-1',
    firstName: 'Sarah',
    lastName: 'Johnson',
    email: 'sarah.johnson@email.com',
    phone: '+1 (555) 123-4567',
    address: {
      street: '123 Main Street',
      city: 'New York',
      state: 'NY',
      country: 'United States',
      zipCode: '10001'
    },
    profilePicture: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    gender: 'female',
    dateOfBirth: '1985-06-15',
    nationality: 'American',
    occupation: 'Marketing Director',
    company: 'Tech Solutions Inc.',
    loyaltyTier: 'platinum',
    loyaltyPoints: 12500,
    lifetimeValue: 28450,
    averageSpend: 485,
    totalStays: 23,
    totalSpent: 28450,
    averageRating: 4.8,
    lastStay: '2024-01-10',
    nextReservation: '2024-02-15',
    preferences: {
      roomType: 'suite',
      floor: 'high',
      bedType: 'king',
      smoking: false,
      specialRequests: ['Ocean view', 'Late checkout']
    },
    communicationPreference: 'email',
    dietaryRestrictions: ['Vegetarian', 'Gluten-free'],
    roomPreferences: ['Ocean view', 'High floor', 'Away from elevator'],
    specialNotes: 'Prefers room 301. Always requests extra pillows.',
    tags: ['Business traveler', 'Frequent guest', 'High spender'],
    status: 'vip',
    bookingHistory: [],
    reviews: [],
    createdAt: '2021-03-15T10:00:00Z',
    updatedAt: '2024-01-10T15:30:00Z'
  },
  {
    id: 'guest-2',
    firstName: 'Michael',
    lastName: 'Chen',
    email: 'michael.chen@email.com',
    phone: '+1 (555) 234-5678',
    address: {
      street: '456 Oak Avenue',
      city: 'San Francisco',
      state: 'CA',
      country: 'United States',
      zipCode: '94105'
    },
    profilePicture: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    gender: 'male',
    dateOfBirth: '1990-11-22',
    nationality: 'Chinese-American',
    occupation: 'Software Engineer',
    company: 'Global Tech Corp',
    loyaltyTier: 'gold',
    loyaltyPoints: 7800,
    lifetimeValue: 15600,
    averageSpend: 325,
    totalStays: 12,
    totalSpent: 15600,
    averageRating: 4.5,
    lastStay: '2024-01-18',
    communicationPreference: 'email',
    roomPreferences: ['City view', 'Work desk', 'High-speed internet'],
    tags: ['Business traveler', 'Tech professional'],
    status: 'active',
    preferences: {
      roomType: 'executive',
      floor: 'any',
      bedType: 'king',
      smoking: false
    },
    bookingHistory: [],
    reviews: [],
    createdAt: '2022-06-20T14:00:00Z',
    updatedAt: '2024-01-18T09:15:00Z'
  },
  {
    id: 'guest-3',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@email.com',
    phone: '+1 (555) 345-6789',
    address: {
      street: '789 Elm Street',
      city: 'Los Angeles',
      state: 'CA',
      country: 'United States',
      zipCode: '90028'
    },
    profilePicture: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    gender: 'female',
    dateOfBirth: '1988-03-10',
    nationality: 'British',
    occupation: 'Fashion Designer',
    company: 'Wilson Designs',
    loyaltyTier: 'silver',
    loyaltyPoints: 3200,
    lifetimeValue: 8900,
    averageSpend: 445,
    totalStays: 5,
    totalSpent: 8900,
    averageRating: 4.9,
    lastStay: '2023-12-20',
    nextReservation: '2024-03-01',
    communicationPreference: 'sms',
    dietaryRestrictions: ['Vegan'],
    roomPreferences: ['Natural light', 'Bathtub', 'Quiet location'],
    specialNotes: 'Allergic to feathers - requires hypoallergenic pillows',
    tags: ['Leisure traveler', 'Design professional', 'Eco-conscious'],
    status: 'active',
    preferences: {
      roomType: 'deluxe',
      floor: 'mid',
      bedType: 'queen',
      smoking: false
    },
    bookingHistory: [],
    reviews: [],
    createdAt: '2023-01-08T11:30:00Z',
    updatedAt: '2023-12-20T16:45:00Z'
  },
  {
    id: 'guest-4',
    firstName: 'Robert',
    lastName: 'Smith',
    email: 'robert.smith@email.com',
    phone: '+1 (555) 456-7890',
    address: {
      street: '321 Pine Road',
      city: 'Chicago',
      state: 'IL',
      country: 'United States',
      zipCode: '60601'
    },
    gender: 'male',
    dateOfBirth: '1975-09-05',
    nationality: 'American',
    occupation: 'CEO',
    company: 'Smith Enterprises',
    loyaltyTier: 'diamond',
    loyaltyPoints: 25000,
    lifetimeValue: 52000,
    averageSpend: 1200,
    totalStays: 35,
    totalSpent: 52000,
    averageRating: 4.6,
    lastStay: '2024-01-05',
    communicationPreference: 'phone',
    roomPreferences: ['Presidential suite', 'Butler service', 'Private check-in'],
    specialNotes: 'Requires airport transfer. Prefers Dom Perignon champagne.',
    tags: ['VIP', 'Executive', 'High value', 'Frequent traveler'],
    status: 'vip',
    preferences: {
      roomType: 'presidential',
      floor: 'top',
      bedType: 'king',
      smoking: false
    },
    bookingHistory: [],
    reviews: [],
    createdAt: '2020-01-15T09:00:00Z',
    updatedAt: '2024-01-05T18:20:00Z'
  }
];

export const statusOptions = [
  { value: 'all', label: 'All Status' },
  { value: 'active', label: 'Active' },
  { value: 'vip', label: 'VIP' },
  { value: 'blacklisted', label: 'Blacklisted' },
  { value: 'inactive', label: 'Inactive' }
];

export const loyaltyOptions = [
  { value: 'all', label: 'All Tiers' },
  { value: 'diamond', label: 'Diamond' },
  { value: 'platinum', label: 'Platinum' },
  { value: 'gold', label: 'Gold' },
  { value: 'silver', label: 'Silver' },
  { value: 'bronze', label: 'Bronze' }
];